[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_anchor_escrow = "579bRZVyduyz69yKogsabHUb4FyBCfSKsQrDyewir4wu"

[programs.devnet]
solana_anchor_escrow = "Fg6PaFzn4Cbd4jn31vgYvo3gNPWieoHRNKjfJQe1TrZF"

[programs.testnet]
solana_anchor_escrow = "Fg6PaFzn4Cbd4jn31vgYvo3gNPWieoHRNKjfJQe1TrZF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
